development: &default
  adapter: postgresql
  database: copyland_development
  min_messages: WARNING

staging:
  <<: *default
  database: copyland_staging

production:
  <<: *default
  database: copyland_production

test: &test
  <<: *default
  database: copyland_test<%= ENV['TEST_ENV_NUMBER'] %>

cucumber:
  <<: *test
